/**
 * Platform detection for store builds.
 *
 * The iOS Xcode project (generated by PWABuilder) sets a custom user-agent
 * suffix of "SeraVaultIOS" so the web app can detect it is running inside
 * the native wrapper and suppress all subscription/checkout UI per Apple
 * App Store guidelines (§ 3.1.3a — Reader App exception).
 *
 * To configure in Xcode, add this to the WKWebView setup:
 *   webView.customUserAgent = (webView.value(forKey: "userAgent") as? String ?? "") + " SeraVaultIOS"
 *
 * The VITE_PLATFORM=ios build flag is kept as a local testing fallback:
 *   VITE_PLATFORM=ios npm run dev
 */
export const IS_IOS_APP =
  import.meta.env.VITE_PLATFORM === 'ios' ||
  (typeof navigator !== 'undefined' && navigator.userAgent.includes('SeraVaultIOS'));
